name: workflow Evento
on:
  push:
    branches: ["main", "feature/*"]
jobs:
  teste:
    runs-on: Ubuntu-latest
    steps:
     - name: Action de Teste
       run: echo "Action executada apenas em main e features"
      
