name: workflow Evento
on:
  push: 
jobs:
  apenas-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Esse Jobs so executa na branch main
    runs-on: ubuntu-latest
    steps:
      - name: Executando na main
        run: echo "Executando comando na main" 
 
