name: workflow Evento
on:
  schedule:
    - cron: "*/2 * * * *"
    - cron: "0 12 1 * *"
jobs:
  teste:
    permissions: write-all
    runs-on: Ubuntu-latest
    steps:
     - name: Action de Teste
       run: echo "Action executada apenas em main e features"
      
