name: workflow concorrencia
run-name: workflow concorrencia ${{ github.run_number }}
on:
  push: 
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  exemplo-fluxo-execucao-01:
    runs-on: ubuntu-latest
    steps:
      - name: Execucao do job teste
        run: |
          sleep 120;
          echo "Action executada job 01"
          
          
  exemplo-fluxo-execucao-02:
    runs-on: ubuntu-latest
    needs: [exemplo-fluxo-execucao-01]
    steps:
      - name: execucao do job teste
        run: |
          sleep 120;
          echo "Action executada job 02"  
