name: workflow Evento
on:
  push: 
jobs:
  apenas-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Esse Jobs so executa na branch main
    runs-on: ubuntu-latest
    steps:
      - name: Executando na main
        run: echo "Executando comando na main" 
  todos:
    runs-on: ubuntu-latest
    steps:
      - name: Execucao em Feature
        if: ${{ contains(github.ref,'refs/heads/feature') }}
        run: echo "Execucao em Feature"
      - name: Execucao em HotFix
        if: ${{ contains(github.ref,'refs/heads/hotfix') }}
        run: echo "Execucao em hotfix"       
      - name: Execucao em main
        if: ${{ github.ref == 'refs/heads/main'}}
        run: echo "Execucao em main"
      - name: Execucao em todos
        run: echo "Execucao em todos"
