name: workflow matriz
on:
  workflow_dispatch:  
jobs:
  exemplo-fluxo-execucao:
    strategy:
      matrix:
        versao: [16,18,20]
        plataforma: ["windows", "linux"]
    runs-on: "${{ matrix.plataforma }}-latest"
    steps:
      - name: Instalacao do node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.versao }}
      - name: Exibicao da versao da plataforma
        run: |
          node --version
          echo ${{ runner.os }}
